function plats = platform_presets(name)
% PLATFORM_PRESETS  Return struct array describing platform loudness policies.
%
% Usage:
%   plats = platform_presets()          -> all platforms
%   plats = platform_presets('Spotify') -> single platform
%
% Fields (per platform):
%   name          : 'AppleMusic' | 'Spotify' | 'YouTube' | 'TikTok'
%   targetLUFS    : streaming loudness target (dB LUFS)
%   tpLimit       : platform-side true-peak ceiling (dBTP)
%   enableBoost   : allow positive gain (boolean)
%   DRC           : 0 = off, 1 = moderate, 2 = strong
%   codecs        : struct array with fields {name, ffmpegCodec, bitrate}
%   eqHF_dB       : high-shelf gain at ~8 kHz after codec (listening EQ)
%   notes         : free text
%
% Platform specifications based on:
%   - Apple Music: -16 LUFS target, Sound Check enabled
%   - Spotify: -14 LUFS target, Normal mode
%   - YouTube: -14 LUFS target, mostly attenuation only
%   - TikTok: -16 LUFS target, mobile-optimized

    % ---------- base definition ----------
    plats = struct('name',{},'targetLUFS',{},'tpLimit',{}, ...
                   'enableBoost',{},'DRC',{},'codecs',{}, ...
                   'eqHF_dB',{},'notes',{});

    % Apple Music ----------------------------------------------------------
    plats(end+1) = struct( ...
        'name',        'AppleMusic', ...
        'targetLUFS',  -16, ...
        'tpLimit',     -1.0, ...
        'enableBoost', true, ...
        'DRC',         1, ...
        'codecs',      codecSet({'aac','opus','ogg'}, {'aac','libopus','libvorbis'}), ...
        'eqHF_dB',     +1.0, ...
        'notes',       'Apple Music Sound Check style');

    % Spotify --------------------------------------------------------------
    plats(end+1) = struct( ...
        'name',        'Spotify', ...
        'targetLUFS',  -14, ...
        'tpLimit',     -1.0, ...
        'enableBoost', true, ...
        'DRC',         1, ...
        'codecs',      codecSet({'aac','opus','ogg'}, {'aac','libopus','libvorbis'}), ...
        'eqHF_dB',     +2.0, ...
        'notes',       'Spotify Normal loudness');

    % YouTube --------------------------------------------------------------
    plats(end+1) = struct( ...
        'name',        'YouTube', ...
        'targetLUFS',  -14, ...
        'tpLimit',     -1.0, ...
        'enableBoost', false, ...   % YouTube mostly attenuates only
        'DRC',         0, ...
        'codecs',      codecSet({'aac','opus','ogg'}, {'aac','libopus','libvorbis'}), ...
        'eqHF_dB',     +3.0, ...
        'notes',       'YouTube loudness normalisation');

    % TikTok ---------------------------------------------------------------
    plats(end+1) = struct( ...
        'name',        'TikTok', ...
        'targetLUFS',  -16, ...
        'tpLimit',     -1.0, ...
        'enableBoost', true, ...
        'DRC',         2, ...
        'codecs',      codecSet({'aac','opus','ogg'}, {'aac','libopus','libvorbis'}), ...
        'eqHF_dB',     +4.0, ...
        'notes',       'Mobile-first platform');

    % ---------- optional single-platform selection ----------
    if nargin >= 1 && ~isempty(name)
        mask = strcmpi({plats.name}, name);
        if any(mask)
            plats = plats(mask);
        else
            error('platform_presets:unknownName', ...
                'Unknown platform name "%s".', name);
        end
    end
end

% ---------- local helper: build default codec set ----------
function C = codecSet(names, ffmpegNames)
    if nargin < 2 || isempty(ffmpegNames)
        ffmpegNames = names;
    end
    bitrates = {'128k','160k','192k'};
    C = struct('name',{},'ffmpegCodec',{},'bitrate',{});
    for i = 1:numel(names)
        C(end+1) = struct( ...
            'name',        names{i}, ...
            'ffmpegCodec', ffmpegNames{i}, ...
            'bitrate',     bitrates{min(i,numel(bitrates))});
    end
end
